### ISSUE TITLE
Cannot deserialize a field named "private"

### ISSUE THREAD

**Issue by green-coder** [hiddenswitch/Meteor-Unity#12]
I ran into a problem while following the Meteor's "simple-todos" tutorial : the fields named `checked` and `private` are both reserved words in C#.

I tried `[JsonName("checked")] bool _checked;` and it worked.
I tried `[JsonName("private")] bool _private;` and it didn't worked - that's the problem.

Do you know a solution?

**Comment by green-coder** [comment]
I think that the problem is with the JsonFx serialization library that you are using.
I am currently using a workaround which is to skip a check in JsonName's class construction:

    public JsonNameAttribute(string jsonName)
    {
      //this.jsonName = EcmaScriptIdentifier.EnsureValidIdentifier(jsonName, false);
      this.jsonName = jsonName;
    }

**Comment by doctorpangloss** [comment]
Thanks, this is a real issue. I'll probably make the change similar to yours.

**Comment by doctorpangloss** [comment]
It is unclear whether or not this has other side effects, so I am going to close it for now and not fix it. Thanks for reporting.
