### ISSUE TITLE
Many compilation warning - logs are flooded

### ISSUE THREAD

**Issue by green-coder** [hiddenswitch/Meteor-Unity#13]
My temporary workaround is to have a file "Assets/smcs.rsp" :

```
-nowarn:0618
-nowarn:0649
```

The problem with this workaround is that it hides the warnings in other parts of my program. It would be nice if we could have the warnings disabled for the Meteor-Unity folder only.

**Comment by doctorpangloss** [comment]
I will address the compilation warnings in v3.1.

**Comment by doctorpangloss** [comment]
Fixed in #16
