### ISSUE TITLE
DDP Reconnect

### ISSUE THREAD

**Issue by silentwarrior** [hiddenswitch/Meteor-Unity#3]
Hello.

I have implemented this on my Unity project (server admin tool) that has about 2000 users.

Great job by the way.

I noticied it doesnt have reconnect function (or i cant find it), would you mind adding one? Because for example, when I do a hotcode push, the server restarts, the "IsConnected" does not change (so i cant manually do a reconnect) but it stops sending and receiving events.

I have half implemented my own system before I saw yours (and moved) and it has reconnect, if you want, i can send you all my code so you can have a look.

**Comment by doctorpangloss** [comment]
This is resolved in the `develop` branch.
