### ISSUE TITLE
Cant login to meteor server 

### ISSUE THREAD

**Issue by Boudz78** [hiddenswitch/Meteor-Unity#31]
Hello I can connect successfully to meteor server  but I can't login:

    yield return Meteor.Connection.Connect("ws://192.168.2.111:3000/websocket");
        Debug.Log("connected");

        //yield return  Meteor.Accounts.LoginWith("mama", "mous3ab4.");

        yield return Accounts.CreateAndLoginWith(string.Format("test{0}@gtest.com", UnityEngine.Random.Range(0, 100000000)),
                                                      string.Format("test{0}", UnityEngine.Random.Range(0, 100000000)),
                                                      "testpassword");

I am sure my meteor server is working properly !?
any help please?

**Comment by apheliagames** [comment]
You probably haven't installed the accounts-password package on your meteor server....
It's needed to login properly...
